// #include <etl/profiles/armv7_no_stl.h>

#ifndef USER_ETL_CONFIGURATION
#define USER_ETL_CONFIGURATION

#define ETL_TARGET_DEVICE_ARM
#define ETL_TARGET_OS_NONE
#define ETL_COMPILER_CLANG
#define ETL_COMPILER_VERSION 6010050

#define ETL_CPP11_SUPPORTED 1
#define ETL_CPP14_SUPPORTED 0
#define ETL_CPP17_SUPPORTED 0
#define ETL_NO_NULLPTR_SUPPORT 1
#define ETL_NO_LARGE_CHAR_SUPPORT 0
#define ETL_CPP11_TYPE_TRAITS_IS_TRIVIAL_SUPPORTED 1

#define ETL_NO_STL

#define ETL_LOG_ERRORS
#define ETL_DEBUG

// #define ETL_USING_EXCEPTIONS

#define ETL_STRING_TRUNCATION_IS_ERROR
//#define ETL_ENABLE_ERROR_ON_STRING_TRUNCATION


#endif
